<?php

/**
 * Perform alterations on language switcher links.
 *
 * A language switcher link may need to point to a different path or use a
 * translated link text before going through the link generator, which will
 * just handle the path aliases.
 *
 * @param array $links
 *   Nested array of links keyed by language code.
 * @param string $type
 *   The language type the links will switch.
 * @param \Drupal\Core\Url $url
 *   The URL the switch links will be relative to.
 */
function custom_sgh_language_switch_links_alter(array &$links, $type, \Drupal\Core\Url $url) {
  $language_interface = \Drupal::languageManager()->getCurrentLanguage();
  $current_language_id = $language_interface->getId();
  unset($links[$current_language_id]);
}

function custom_sgh_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  dsm($form_id);
  dsm($_GET['email']);
  if($form_id == 'mailchimp_signup_subscribe_page_subscribe_to_our_news_letter_form') {
    dsm($form);
  }
}