custom_header_image.header_image.*:
  type: config_entity
  label: 'Header image config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    image_style:
      type: string
    alt:
      type: string
      label: 'Alt text'
    header_image:
      type: integer
    paths:
      type: sequence
      sequence:
        type: string
